serial:
  port: /dev/ttyUSB0
  baud-rate: 19200

mqtt-broker:
  url: tcp://${domain.name}:1883
  id: house-news
  persist-dir: ${java.io.tmpdir}
  
sensor:
  location: mulbetet49  

logging:
  level:
    se.aceone.housenews: INFO
    
